//Karina Alejandra Arriaza Ortiz 9959-24-14190
package Vista;

import Controlador.clsCarreras;
import Modelo.CarrerasDAO;
import java.io.File;
import java.sql.Connection;

public class frmCarreras extends javax.swing.JFrame {

private final CarrerasDAO dao = new CarrerasDAO();

    public frmCarreras() {
        initComponents();
        setResizable(true);
        setTitle("Carreras");
        cargarTabla();
        configurarSeleccionTabla();
        setDefaultCloseOperation(javax.swing.JInternalFrame.DISPOSE_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Ayuda = new javax.swing.JButton();
        Reporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        facultad = new javax.swing.JTextField();
        estatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N
        jLabel1.setText("Carreras");

        Agregar.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Actualizar.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        Eliminar.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Ayuda.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N
        Ayuda.setText("Ayuda");
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });

        Reporte.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N
        Reporte.setText("Reporte");
        Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Facultad", "Estatus"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N
        jLabel4.setText("Facultad C:");

        jLabel5.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N
        jLabel5.setText("Estatus:");

        id.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N

        nombre.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N

        facultad.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N

        estatus.setFont(new java.awt.Font("Corbel", 2, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(3, 3, 3)
                                        .addComponent(facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(estatus, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Buscar)
                                    .addComponent(Agregar))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Eliminar)
                                    .addComponent(Actualizar))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Reporte)
                                    .addComponent(Ayuda))
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Eliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ayuda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Reporte))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Agregar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Buscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(facultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
// Verifica que todos los campos estén completos
if (!camposCompletos()) {
    return;
}

try {

    // Obtiene los datos del formulario
    clsCarreras carrera = getCarreraDeFormulario();

    // Guarda la carrera en la base de datos
    CarrerasDAO dao = new CarrerasDAO();
    int resultado = dao.ingresaCarrera(carrera);

    if (resultado > 0) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Carrera registrado correctamente.",
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Actualiza la tabla
        cargarTabla();

        // Limpia el formulario
        limpiarCampos();

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No fue posible registrar la carrera.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error al agregar: " + e.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_AgregarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
if (id.getText().trim().isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Ingrese un ID para buscar.",
            "Atención",
            javax.swing.JOptionPane.WARNING_MESSAGE);

    return;
}

try {

    int codigo = Integer.parseInt(id.getText().trim());

    CarrerasDAO dao = new CarrerasDAO();
    clsCarreras carrera = dao.getCarrera(codigo);

    if (carrera != null) {

        nombre.setText(carrera.getCarnombre());
        facultad.setText(carrera.getFaccodigo());
        estatus.setText(carrera.getCarestatus());

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Carrera encontrada correctamente.");

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se encontró una carrera con ID: " + codigo,
                "Sin resultados",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        limpiarCampos();
    }

} catch (NumberFormatException ex) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "El ID debe ser un número válido.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error al buscar: " + e.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_BuscarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
// Verifica que se haya seleccionado un libro para actualizar
if (id.getText().trim().isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(this,
        "Seleccione un libro de la tabla o ingrese un ID.",
        "Atención",
        javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}

// Verifica que los campos obligatorios estén completos
if (!camposCompletos()) return;

try {

    // Obtiene los datos del formulario
    clsCarreras carrera = getCarreraDeFormulario();

    carrera.setCarcodigo(
        Integer.parseInt(id.getText().trim()));

    int resultado = carrera.setModificarCarreras(carrera);

    if (resultado > 0) {

        javax.swing.JOptionPane.showMessageDialog(this,
            "Carrera actualizada correctamente.",
            "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Recarga la tabla
        cargarTabla();

        // Limpia los campos
        limpiarCampos();

    } else {

        javax.swing.JOptionPane.showMessageDialog(this,
            "No se pudo actualizar la carrera.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }

} catch (NumberFormatException ex) {

    javax.swing.JOptionPane.showMessageDialog(this,
        "El ID debe ser un número válido.",
        "Error",
        javax.swing.JOptionPane.ERROR_MESSAGE);

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(this,
        "Error al actualizar: " + e.getMessage(),
        "Error",
        javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_ActualizarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
// Verifica que el campo ID no esté vacío
if (id.getText().trim().isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Seleccione un libro de la tabla o ingrese un ID.",
            "Atención",
            javax.swing.JOptionPane.WARNING_MESSAGE);

    return;
}

// Solicita confirmación
int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro de que desea eliminar esta carrera?",
        "Confirmar eliminación",
        javax.swing.JOptionPane.YES_NO_OPTION);

if (confirm != javax.swing.JOptionPane.YES_OPTION) {
    return;
}

try {

    int codigo = Integer.parseInt(id.getText().trim());

    clsCarreras carrera = new clsCarreras();
    carrera.setCarcodigo(codigo);

    CarrerasDAO dao = new CarrerasDAO();
    int resultado = dao.borraCarrera(carrera);

    if (resultado > 0) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Carrera eliminada correctamente.",
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        cargarTabla();
        limpiarCampos();

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se pudo eliminar la carrera.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }

} catch (NumberFormatException ex) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "El ID debe ser un número válido.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error al eliminar: " + e.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_EliminarActionPerformed

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed
// Inicia un bloque try-catch para manejar posibles errores
try {

    // Define la ruta donde se encuentra el archivo de ayuda
    String ruta = "src\\main\\java\\Ayudas\\Bancos\\Ayuda Bancos.chm";

    // Crea un objeto File para verificar el archivo
    File archivo = new File(ruta);

    // Verifica si el archivo existe
    if (archivo.exists()) {

        // Ejecuta el archivo de ayuda usando hh.exe
        Runtime.getRuntime().exec("hh.exe \"" + ruta + "\"");

    } else {

        // Muestra un mensaje en consola si no se encuentra la ayuda
        System.out.println("La ayuda no fue encontrada");
    }

} catch (Exception ex) {

    // Muestra el error en consola si ocurre una excepción
    ex.printStackTrace();
}
    }//GEN-LAST:event_AyudaActionPerformed

    private void ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteActionPerformed
// Declara la conexión a la base de datos
Connection conn = null;

try {

    // Obtiene la conexión con la base de datos
    conn = Modelo.Conexion.getConnection();

    // Define la ruta donde se encuentra el archivo .jrxml
    String ruta = new java.io.File("").getAbsolutePath()
        + "\\src\\main\\java\\Reportes\\Libreria.jrxml";

    // Muestra la ruta en consola para verificarla
    System.out.println("Buscando reporte en: " + ruta);

    // Verifica si el archivo del reporte existe
    java.io.File archivo = new java.io.File(ruta);

    if (!archivo.exists()) {

        // Muestra un mensaje si el archivo no se encuentra
        javax.swing.JOptionPane.showMessageDialog(this,
            "No se encontró el archivo del reporte en:\n" + ruta,
            "Archivo no encontrado",
            javax.swing.JOptionPane.ERROR_MESSAGE);

        return;
    }

    // Crea un mapa para enviar parámetros al reporte
    java.util.Map<String, Object> parametros =
        new java.util.HashMap<>();

    // Compila el archivo .jrxml
    net.sf.jasperreports.engine.JasperReport reporte =
        net.sf.jasperreports.engine.JasperCompileManager
            .compileReport(ruta);

    // Llena el reporte con los datos de la base de datos
    net.sf.jasperreports.engine.JasperPrint print =
        net.sf.jasperreports.engine.JasperFillManager
            .fillReport(reporte, parametros, conn);

    // Exporta el reporte a un archivo PDF
    net.sf.jasperreports.engine.JasperExportManager
        .exportReportToPdfFile(print, "reporte.pdf");

    // Crea un visor para mostrar el reporte
    net.sf.jasperreports.swing.JRViewer viewer =
        new net.sf.jasperreports.swing.JRViewer(print);

    // Crea una ventana para visualizar el reporte
    javax.swing.JFrame frame =
        new javax.swing.JFrame("Reporte de Estado Conciliacion");

    frame.setSize(800, 600);
    frame.setLocationRelativeTo(null);

    // Define que la ventana solo se cierre a sí misma
    frame.setDefaultCloseOperation(
        javax.swing.JFrame.DISPOSE_ON_CLOSE);

    // Agrega el visor del reporte a la ventana
    frame.add(viewer);

    // Hace visible la ventana
    frame.setVisible(true);

} catch (Exception e) {

    // Muestra el error en consola
    e.printStackTrace();

    // Muestra un mensaje de error al usuario
    javax.swing.JOptionPane.showMessageDialog(this,
        "Error al generar el reporte:\n" + e.getMessage(),
        "Error",
        javax.swing.JOptionPane.ERROR_MESSAGE);

} finally {

    // Cierra la conexión a la base de datos
    if (conn != null) {
        try {
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
    }//GEN-LAST:event_ReporteActionPerformed
// ── Llena la tabla con todos los estados de conciliación ────────────────────
private void cargarTabla() {

    javax.swing.table.DefaultTableModel modelo =
        new javax.swing.table.DefaultTableModel(
            new String[]{
                "ID",
                "Nombre",
                "Facultad",
                "Estatus"
            }, 0) {

        @Override
        public boolean isCellEditable(int r, int c) {
            return false;
        }
    };

    for (clsCarreras car : new clsCarreras().getListaCarreras()) {
        modelo.addRow(new Object[]{
            car.getCarcodigo(),
            car.getCarnombre(),
            car.getFaccodigo(),
            car.getCarestatus()
        });
    }

    jTable1.setModel(modelo);
}

// ── Limpia todos los campos ──────────────────────────────────
private void limpiarCampos() {
    id.setText("");
    nombre.setText("");
    facultad.setText("");
    estatus.setText("");
    jTable1.clearSelection();
}

// ── Valida que los campos no estén vacíos ───────────────────
private boolean camposCompletos() {

    if (id.getText().trim().isEmpty(){
        javax.swing.JOptionPane.showMessageDialog(this,
                "Complete todos los campos de la carrera.",
                "Campos incompletos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return false;
    }

    return true;
}
private void configurarSeleccionTabla() {

    jTable1.getSelectionModel().addListSelectionListener(e -> {

        if (!e.getValueIsAdjusting()
                && jTable1.getSelectedRow() != -1) {

            int fila = jTable1.getSelectedRow();

            id.setText(
                    jTable1.getValueAt(fila, 0).toString());

            nombre.setText(
                    jTable1.getValueAt(fila, 1).toString());

            facultad.setText(
                    jTable1.getValueAt(fila, 2).toString());

            estatus.setText(
                    jTable1.getValueAt(fila, 3).toString());
        }
    });
}

// ── Crea el objeto clsLibreria desde los campos del formulario ─
private clsCarreras getCarreraDeFormulario() {

    clsCarreras carrera = new clsCarreras(
        0, // ID lo genera MySQL (AUTO_INCREMENT)

        nombre.getText().trim(),
        facultad.getText().trim(),
        estatus.getText().trim()
    );

    return carrera;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCarreras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Ayuda;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Reporte;
    private javax.swing.JTextField estatus;
    private javax.swing.JTextField facultad;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
